MS-2575 library init + repository structure + README + spec coverage + jsdoc

diff --git a/scripts/git-hooks/pre-push b/scripts/git-hooks/pre-push
--- a/scripts/git-hooks/pre-push
+++ b/scripts/git-hooks/pre-push
@@ -2,7 +2,7 @@
 
 ## Run tests
 echo "###### Running tests ######"
-OUTPUT=`npm test`
+OUTPUT=`npm run coverage:ci`
 
 if (( $? != 0 )); then
     echo "###### Tests failed ######"
@@ -10,3 +10,14 @@ if (( $? != 0 )); then
     exit 1
 fi
 echo "###### tests passed correctly ######"
+
+## Run jsdoc
+echo "###### Running jsdoc ######"
+OUTPUT=`npm run jsdoc`
+
+if (( $? != 0 )); then
+    echo "###### jsdoc failed ######"
+    echo "$OUTPUT"
+    exit 1
+fi
+echo "###### jsdoc passed correctly ######"
